import { Component } from '@angular/core';
import { CommonFunctionService } from 'src/app/shared/Service-common/common-function.service';

@Component({
  selector: 'app-anticipating-setup',
  templateUrl: './anticipating-setup.component.html',
  styleUrl: './anticipating-setup.component.scss'
})
export class AnticipatingSetupComponent {
  onTicketAgingId = 1;
  ProjectList:any[]=[
    {
      "companyId": 1,
      "companyName": "SS Tech Pte Ltd",
      "clientId": 1,
      "clientName": "McConnell Dowell South East Asia Pte Ltd",
      "departmentId": 2,
      "departmentCode": "TWRP",
      "departmentName": "Tuas Water Reclamation Plant",
      "contactPerson1": "Sathish Sivasothy",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": true,
      "maintenanceTypeId": 1,
      "maintenanceType": "Defect Liability Period",
      "maintenanceStatusId": 28,
      "maintenanceStatusName": "Active",
      "maintenanceStartDate": "07/10/2024 00:00:00",
      "maintenanceEndDate": "07/16/2024 00:00:00",
      "warrentyStatusId": 28,
      "warrentyStatusName": "Active",
      "warrentyStartDate": "07/13/2024 00:00:00",
      "warrentyEndDate": "07/15/2024 00:00:00",
      "maintenanceRemark": null,
      "isProjectManagement": false,
      "projectManagementStatusId": 1,
      "projectManagementStatusName": "Not Applicable"
    },
    {
      "companyId": 1,
      "companyName": "SS Tech Pte Ltd",
      "clientId": 2,
      "clientName": "Head Office Singapore",
      "departmentId": 4,
      "departmentCode": "HO",
      "departmentName": "Singapore Branch",
      "contactPerson1": "Roy Png",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": true,
      "maintenanceTypeId": 3,
      "maintenanceType": "Inhouse Support",
      "maintenanceStatusId": 28,
      "maintenanceStatusName": "Active",
      "maintenanceStartDate": "07/01/2024 00:00:00",
      "maintenanceEndDate": "07/31/2030 00:00:00",
      "warrentyStatusId": 1,
      "warrentyStatusName": "Not Applicable",
      "warrentyStartDate": null,
      "warrentyEndDate": null,
      "maintenanceRemark": null,
      "isProjectManagement": false,
      "projectManagementStatusId": 1,
      "projectManagementStatusName": "Not Applicable"
    },
    {
      "companyId": 2,
      "companyName": "SS Surveillance & Communication Sdn Bhd",
      "clientId": 3,
      "clientName": "Head Office Malaysia",
      "departmentId": 5,
      "departmentCode": "HOM",
      "departmentName": "Johor Bahru Regional Office",
      "contactPerson1": "Subramaniam Malibaba",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": false,
      "maintenanceTypeId": null,
      "maintenanceType": null,
      "maintenanceStatusId": 1,
      "maintenanceStatusName": "Not Applicable",
      "maintenanceStartDate": null,
      "maintenanceEndDate": null,
      "warrentyStatusId": 1,
      "warrentyStatusName": "Not Applicable",
      "warrentyStartDate": null,
      "warrentyEndDate": null,
      "maintenanceRemark": null,
      "isProjectManagement": false,
      "projectManagementStatusId": 1,
      "projectManagementStatusName": "Not Applicable"
    },
    {
      "companyId": 2,
      "companyName": "SS Surveillance & Communication Sdn Bhd",
      "clientId": 5,
      "clientName": "Exyte Malaysia Sdn. Bhd.",
      "departmentId": 6,
      "departmentCode": "MDC",
      "departmentName": "Microsoft Data Centre",
      "contactPerson1": "Kavimathi Supramaniam",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": false,
      "maintenanceTypeId": null,
      "maintenanceType": null,
      "maintenanceStatusId": 1,
      "maintenanceStatusName": "Not Applicable",
      "maintenanceStartDate": null,
      "maintenanceEndDate": null,
      "warrentyStatusId": 1,
      "warrentyStatusName": "Not Applicable",
      "warrentyStartDate": null,
      "warrentyEndDate": null,
      "maintenanceRemark": null,
      "isProjectManagement": false,
      "projectManagementStatusId": 1,
      "projectManagementStatusName": "Not Applicable"
    },
    {
      "companyId": 1,
      "companyName": "SS Tech Pte Ltd",
      "clientId": 8,
      "clientName": "National University of Singapore (NUS)",
      "departmentId": 7,
      "departmentCode": "NUS",
      "departmentName": "NUS Access Control System",
      "contactPerson1": "Gong Wei",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": false,
      "maintenanceTypeId": null,
      "maintenanceType": null,
      "maintenanceStatusId": 1,
      "maintenanceStatusName": "Not Applicable",
      "maintenanceStartDate": null,
      "maintenanceEndDate": null,
      "warrentyStatusId": 1,
      "warrentyStatusName": "Not Applicable",
      "warrentyStartDate": null,
      "warrentyEndDate": null,
      "maintenanceRemark": null,
      "isProjectManagement": true,
      "projectManagementStatusId": 80,
      "projectManagementStatusName": "Project Initated"
    },
    {
      "companyId": 2,
      "companyName": "SS Surveillance & Communication Sdn Bhd",
      "clientId": 7,
      "clientName": "Bank Simpanan Nasional",
      "departmentId": 8,
      "departmentCode": "145",
      "departmentName": "BSN-Maintenance",
      "contactPerson1": "Sjn.Rashid",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": false,
      "maintenanceTypeId": null,
      "maintenanceType": null,
      "maintenanceStatusId": 1,
      "maintenanceStatusName": "Not Applicable",
      "maintenanceStartDate": null,
      "maintenanceEndDate": null,
      "warrentyStatusId": 1,
      "warrentyStatusName": "Not Applicable",
      "warrentyStartDate": null,
      "warrentyEndDate": null,
      "maintenanceRemark": null,
      "isProjectManagement": false,
      "projectManagementStatusId": 1,
      "projectManagementStatusName": "Not Applicable"
    },
    {
      "companyId": 1,
      "companyName": "SS Tech Pte Ltd",
      "clientId": 1,
      "clientName": "McConnell Dowell South East Asia Pte Ltd",
      "departmentId": 9,
      "departmentCode": "SSG",
      "departmentName": "South Staging Ground 2",
      "contactPerson1": "Sathish Sivasothy",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": false,
      "maintenanceTypeId": null,
      "maintenanceType": null,
      "maintenanceStatusId": 1,
      "maintenanceStatusName": "Not Applicable",
      "maintenanceStartDate": null,
      "maintenanceEndDate": null,
      "warrentyStatusId": 1,
      "warrentyStatusName": "Not Applicable",
      "warrentyStartDate": null,
      "warrentyEndDate": null,
      "maintenanceRemark": null,
      "isProjectManagement": false,
      "projectManagementStatusId": 1,
      "projectManagementStatusName": "Not Applicable"
    },
    {
      "companyId": 2,
      "companyName": "SS Surveillance & Communication Sdn Bhd",
      "clientId": 3,
      "clientName": "Head Office Malaysia",
      "departmentId": 10,
      "departmentCode": "WH001",
      "departmentName": "Warehouse",
      "contactPerson1": "Mashita",
      "currencyCode": null,
      "departmentStatusId": 28,
      "departmentStatusName": "Active",
      "currentProcessId": 1,
      "currentProcessName": "Not Applicable",
      "isSaftyAuditDone": false,
      "isAwarded": true,
      "isMaintenance": false,
      "maintenanceTypeId": null,
      "maintenanceType": null,
      "maintenanceStatusId": 1,
      "maintenanceStatusName": "Not Applicable",
      "maintenanceStartDate": null,
      "maintenanceEndDate": null,
      "warrentyStatusId": 1,
      "warrentyStatusName": "Not Applicable",
      "warrentyStartDate": null,
      "warrentyEndDate": null,
      "maintenanceRemark": null,
      "isProjectManagement": true,
      "projectManagementStatusId": 80,
      "projectManagementStatusName": "Project Initated"
    },]

constructor(  private commonFunctionService: CommonFunctionService,
){

}

    returnStatusBadgeClassesStatus(id: any) {
      return this.commonFunctionService.returnStatusBadgeClasses(id);
    }
}
